const accessToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbjEiLCJpYXQiOjE2OTU0MTMzMTIsImV4cCI6MTY5NTQxNjkxMn0.vaoSHYIUeToljPfMTu6seQc0bMgwQ5KmT7Pw7FzH3nM";

  export default accessToken;
